@startuml
!include ./../no.ks.fiks.saksfaser.v1.felles.eksternnoekkel/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.journalnummer/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.referansejournalpost/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.saksjournalpostnummer/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.referansedokumentfil/classdiagram.pu


class Milepel {
    *milepelId: string
    *beskrivelse: string
    milepeltype: Milepeltype
    frist: date
    utfoert: date
    planlagtUtfoert: date
    *intern: boolean
    referanseJournalpost: ReferanseJournalpost
    referanseDokument: ReferanseDokumentfil
    *status: MilepelStatusEnum
}

note top of Milepel : planlagtUtfoert er hvis man har laget en milepel plan \nså kan man sette denne datoen for når det er planlagt å være ferdig

Milepel -- Milepeltype

note top of Milepeltype : Eksempler: \nBestilling av oppstartsmøte (BO)\nGjennomført oppstartsmøte (OM)\nMottak av planforslag

note bottom of Milepel: frist og utfoert ikke påkrevd


class Milepeltype {
    +kodeverdi: string
    +kodebeskrivelse: string
}

Milepel -- ReferanseJournalpost
Milepel -- ReferanseDokumentfil

class ReferanseDokumentfil {
}

Milepel -- MilepelStatusEnum
ReferanseJournalpost -- EksternNoekkel
ReferanseJournalpost -- SaksJournalpostnummer
ReferanseJournalpost -- Journalnummer

enum MilepelStatusEnum {
    +Naadd
    +IkkeNaadd
    +Planlagt
}

@enduml