@startuml

class Milepel {
    +systemId: string
    +beskrivelse: string
    +kategori: Milepeltype
    +frist: date
    +utfoert: date
    +journaldato: date
    +intern: boolean
    +referanseJournalpost: string
    +referanseDokument: string
    +erStart: boolean
    +erSlutt: boolean
    +status: MilepelStatusEnum
    +erGlobal: boolean
    +dokumenter: Dokument[]
}

Milepel -- Milepeltype

class Milepeltype {
    +kodeverdi: string
    +kodebeskrivelse: string
}

Milepel -- MilepelStatusEnum
Milepel -* Dokument

enum MilepelStatusEnum {
    +Nådd
    +Planlagt
}


class Dokument {
    +id: string
    +tittel: string
    +filnavn: string
    +dokumenttype: Dokumenttype
    +referanseDokumentfil: ReferanseDokumentfil
    +mimetype: string
    +dokumentsdato: date
    +arkivnavn: string
}

note top of Dokument : Hentet definisjon fra Fiks Plan

Dokument -- Dokumenttype
Dokument -- ReferanseDokumentfil

class Dokumenttype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ReferanseDokumentfil {
    +id: string
    +url: string
}


@enduml