@startuml
!include ./../no.ks.fiks.saksfaser.v1.felles.dokument/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.fase/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.milepel/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.saksnummer/classdiagram.pu

class SaksfaserHentResultat {
    +saksnummer: Saksnummer
    +sakstittel: string
    +saksansvarlig: string
    +faser: Fase[]
}

note left of SaksfaserHentResultat::faser
    Rekkefølgen av Fase objekter i faser er signifikant.
    Det er den rekkefølgen fasene har.
end note

SaksfaserHentResultat -* Fase
SaksfaserHentResultat -- Saksnummer


note right of Fase::faseid
    Faseid brukes alene (ikke sammen med saksnummer) for å hente en enkelt fase
    Den må dermed være unik 
end note

Fase -- Milepel
Fase -* Dokument
Milepel -* Dokument

@enduml