@startuml
class SaksfaserHentResultat {
    +byggesak: Byggesak
    +faser: Fase[]
}

SaksfaserHentResultat -- Byggesak
SaksfaserHentResultat -* Fase

note top of Byggesak : Skal byggesak være med?


@enduml