@startuml

class Korrespondansepart {
    *korrespondanseparttype: Korrespondanseparttype
    *korrespondansepartnavn: string
}

Korrespondansepart .. Korrespondanseparttype

class Korrespondanseparttype <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

@enduml