@startuml
class Byggesak {
    +saksnummer: Saksnummer
    +systemId: string
    +tittel: string
    +tiltakstype: Kode?
    +adresse: Adresse
    +registrerDato: dato
    +avsluttetDato: dato
    +gjeldendePlaner: NasjonalArealplanId[]
    +matrikkelopplysninger: Matrikkelopplysninger
    +posisjon: Posisjon
    +referanseAndreSaker: Saksnummer[]
    +referanseKlagesaker: Saksnummer[]
}

Byggesak -* Saksnummer
Byggesak -* NasjonalArealplanId
Byggesak -- Matrikkelopplysninger
Byggesak -- Posisjon
Byggesak -- Kode

@enduml