@startuml

class ReferanseJournalpost {
    systemId: string
    registreringsId: string
    journalnummer: Journalnummer
    saksJournalpostnummer: SaksJournalpostnummer
    referanseEksternNoekkel: EksternNoekkel
}

note left of ReferanseJournalpost {
    Ingen av feltene er påkrevd,
     men man kan velge hvilken identifikator man vil bruke
}

@enduml