@startuml
!include ./../no.ks.fiks.saksfaser.v1.felles.skjerming/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.gradering/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.dokumentbeskrivelse/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.korrespondansepart/classdiagram.pu

class Journalpost {
    systemId: string
    skjerming: Skjerming
    gradering: Gradering
    dokumentbeskrivelser: Dokumentbeskrivelse[]
    registreringsid: string
    tittel: string
    offentligTittel: string
    korrespondanseparter: Korrespondansepart[]
    journalaar: integer
    journalsekvensnummer: integer
    journalpostnummer: integer
    journalposttype: Journalposttype
    journalstatus: Journalstatus
    journaldato: date
    dokumentetsDato: date
}

Journalpost .. Skjerming
Journalpost .. Gradering
Journalpost .* Dokumentbeskrivelse
Journalpost .* Korrespondansepart
Journalpost .. Journalposttype
Journalpost .. Journalstatus



class Journalposttype <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

class Journalstatus <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}


@enduml