@startuml
!include ./../no.ks.fiks.saksfaser.v1.felles.referansedokumentfil/classdiagram.pu

class Dokument {
    *id: string
    filnavn: string
    dokumenttype: Dokumenttype
    referanseDokumentfil: ReferanseDokumentfil
    mimetype: string
    dokumentsdato: date
    arkivnavn: string
    filstoerrelse: int
}

note top of Dokument : Hentet definisjon fra Fiks Plan

Dokument -- ReferanseDokumentfil

@enduml