@startuml
!include ./../no.ks.fiks.saksfaser.v1.felles.referansedokumentfil/classdiagram.pu

class Dokument {
    *id: string
    *filnavn: string
    *referanseDokumentfil: ReferanseDokumentfil
    mimetype: string
    dokumentdato: date
    arkivnavn: string
    filstoerrelse: integer
}

note top of Dokument : Hentet definisjon fra Fiks Plan

Dokument .. ReferanseDokumentfil

@enduml