@startuml
!include ./../no.ks.fiks.saksfaser.v1.felles.referansejournalpost/classdiagram.pu
!include ./../no.ks.fiks.saksfaser.v1.felles.dokument/classdiagram.pu

class Fase {
    *faseId: string
    *fasenavn: string
    *kategori: Fasekategori
    *status: FaseStatusEnum
    startDato: date
    sluttDato: date
    milepeler: Milepel[]
    vedtak: Vedtak
    journalpost: Journalpost[]
}

Fase .. Journalpost

class Journalpost {
    systemId: string
    skjerming: Skjerming
    gradering: Gradering
    dokumentbeskrivelse: Dokumentbeskrivelse[]
    registreringsId: string
    tittel: string
    offentligTittel: string
    korrespondansepart: Korrespondansepart
    journalaar: number
    journalsekvensnummer: number
    journalpostnummer: number
    journalposttype: Journalposttype
    journalstatus: Journalstatus
    journaldato: date
    dokumentetsDato: date
}

Journalpost .. Journalposttype
Journalpost .. Journalstatus
Journalpost .. Dokumentbeskrivelse
Dokumentbeskrivelse .. Gradering
Dokumentbeskrivelse .. Skjerming

class Journalposttype <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

class Journalstatus <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

class Skjerming {
    *tilgangsrestriksjon: Tilgangsrestriksjon
    *skjermingshjemmel: string
    skjermingOpphoererDato: date
    skjermingOpphoererAksjon: date
}

Skjerming .. Tilgangsrestriksjon

class Tilgangsrestriksjon <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

class Gradering {
   *grad: Grad
   *graderingsdato: date
   *gradertAv: string
   nedgraderingsdato: date
   nedgradertAv: string
}

class Grad <<Kode>> {
    *kodeverdi: string
        kodebeskrivelse: string
}

class Dokumentbeskrivelse {
    systemId: string
    dokumenttype: Dokumenttype
    dokumentstatus: Dokumentstatus
    dokumentobjekt: Dokument
}

Dokumentbeskrivelse .. Dokumenttype
Dokumentbeskrivelse .. Dokumentstatus
Dokumentbeskrivelse .. Dokument

class Dokumenttype <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}


class Dokumentstatus <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

note top of Fase : En fase er i hovedsak det som hender mellom to milepeler.\nInterne faser sendes ikke ut ved denne protokollen. Vi kutter derfor ut Global flagg.

note right of Fase::faseid
    Faseid brukes alene (ikke sammen med saksnummer) for å hente en enkelt fase
    Den må dermed være unik 
end note 

Fase .. Vedtak
Fase .. FaseStatusEnum
Fase .. Fasekategori

enum FaseStatusEnum {
    +Planlagt
    +UnderArbeid
    +Utfoert
}

note top of Vedtak : Eksempler:\ngodkjent\ndelvis godkjent\navslått\navvist 

class Vedtak <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

class Fasekategori <<Kode>> {
    *kodeverdi: string
    kodebeskrivelse: string
}

note bottom of Fasekategori : Se gjerne Byggesaksbehandling::Prosesskategori\n fra NPS\nVi må få avklart denne kodelisten\nVi må ha en som er generell som betyr at det ikke er fastsatt hvis kategori skal være required.\nEksempler:\nKlage\nHøring 


@enduml