@startuml

class Fase {
    +fasenavn: string
    +faseid: string
    +kategori: Fasekategori
    +milepeler: Milepel[]
    +status: FaseStatusEnum
    +vedtak: Vedtak
    +dokumenter: Dokument[]
}

note top of Fase : En fase er i hovedsak det som hender mellom to milepeler.\nInterne faser sendes ikke ut ved denne protokollen. Vi kutter derfor ut Global flagg.

note right of Fase::faseid
    Faseid brukes alene (ikke sammen med saksnummer) for å hente en enkelt fase
    Den må dermed være unik 
end note 

Fase -- Vedtak
Fase -- FaseStatusEnum
Fase -- Fasekategori

enum FaseStatusEnum {
    +Planlagt
    +UnderArbeid
    +Utfoert
}

note top of Vedtak : Eksempler:\ngodkjent\ndelvis godkjent\navslått\navvist 

class Vedtak <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Fasekategori <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

note bottom of Fasekategori : Se gjerne Byggesaksbehandling::Prosesskategori\n fra NPS\nVi må få avklart denne kodelisten\nEksempler:\nKlage\nHøring 


@enduml