@startuml

class HentSaksfaseResultat {
    +fase: Fase
}

HentSaksfaseResultat -- Fase

class Fase {
    +fasenavn: string
    +faseid: string
    +milepeler: Milepel[]
    +global: boolean
    +status: FaseStatusEnum
    +dokumenter: Dokument[]
}

Fase -* Dokument
Fase -- Milepel

class Milepel {
    +systemId: string
    +beskrivelse: string
    +kategori: Kode
    +frist: date
    +utfoert: date
    +journaldato: date
    +intern: boolean
    +referanseJournalpost: string
    +referanseDokument: string
    +erStart: boolean
    +erSlutt: boolean
    +status: MilepelStatusEnum
    +erGlobal: boolean
    +dokumenter: Dokument[]
}

Milepel -- MilepelStatusEnum
Milepel -* Dokument

enum MilepelStatusEnum {
    +Nådd
    +Planlagt
}

note top of Dokument : Hentet definisjon fra Fiks Plan

class Dokument {
    +tittel: string
    +dokumenttype: Dokumenttype
    +referanseDokumentfil: ReferanseDokumentfil
    +mimetype: string
    +dokumentsdato: date
    +arkivnavn: string
}

Dokument -- Dokumenttype
Dokument -- ReferanseDokumentfil

class Dokumenttype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ReferanseDokumentfil {
    +id: string
    +url: string
}

@enduml